using AutoMapper;
using ExpressDesk360.Model.Dtos.StockModule.FaultType.Commands;
using ExpressDesk360.Model.Dtos.StockModule.FaultType.Queries;
using ExpressDesk360.Model.Dtos.StockModule.Stock.Commands;
using ExpressDesk360.Model.Dtos.StockModule.Stock.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockBrand.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockBrand.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockGroup.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockGroup.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockGroupBrandMap.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockGroupBrandMap.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockGroupFaultTypeMap.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockGroupFaultTypeMap.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockMovement.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockMovement.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockMovementStockSerialMap.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockMovementStockSerialMap.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockMovementType.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockMovementType.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockSerial.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockSerial.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockSerialWarranty.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockSerialWarranty.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockType.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockType.Queries;
using ExpressDesk360.Model.Dtos.StockModule.StockTypeGroupMap.Commands;
using ExpressDesk360.Model.Dtos.StockModule.StockTypeGroupMap.Queries;
using ExpressDesk360.Model.Dtos.StockModule.Warehouse.Commands;
using ExpressDesk360.Model.Dtos.StockModule.Warehouse.Queries;
using ExpressDesk360.Model.Entities.StockModule;

namespace ExpressDesk360.Business.Mappings;

public class StockModuleMappingProfiles : Profile
{
    public StockModuleMappingProfiles()
    {
        CreateMap<Stock, Stock>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Stock, StockDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.ModelName, opt => opt.MapFrom(src => src.ModelName)).ForMember(dest => dest.ModelCode, opt => opt.MapFrom(src => src.ModelCode)).ForMember(dest => dest.ModelType, opt => opt.MapFrom(src => src.ModelType)).ForMember(dest => dest.UnitId, opt => opt.MapFrom(src => src.UnitId)).ForMember(dest => dest.SerialTracking, opt => opt.MapFrom(src => src.SerialTracking)).ForMember(dest => dest.VirtualSeries, opt => opt.MapFrom(src => src.VirtualSeries)).ForMember(dest => dest.SerialNumberStart, opt => opt.MapFrom(src => src.SerialNumberStart)).ForMember(dest => dest.Vat, opt => opt.MapFrom(src => src.Vat)).ForMember(dest => dest.PurchasePrice, opt => opt.MapFrom(src => src.PurchasePrice)).ForMember(dest => dest.PurchaseCurrencyId, opt => opt.MapFrom(src => src.PurchaseCurrencyId)).ForMember(dest => dest.SalePrice, opt => opt.MapFrom(src => src.SalePrice)).ForMember(dest => dest.SalePriceCurrencyId, opt => opt.MapFrom(src => src.SalePriceCurrencyId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockCreateDto, Stock>().ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.ModelName, opt => opt.MapFrom(src => src.ModelName)).ForMember(dest => dest.ModelCode, opt => opt.MapFrom(src => src.ModelCode)).ForMember(dest => dest.ModelType, opt => opt.MapFrom(src => src.ModelType)).ForMember(dest => dest.UnitId, opt => opt.MapFrom(src => src.UnitId)).ForMember(dest => dest.SerialTracking, opt => opt.MapFrom(src => src.SerialTracking)).ForMember(dest => dest.VirtualSeries, opt => opt.MapFrom(src => src.VirtualSeries)).ForMember(dest => dest.SerialNumberStart, opt => opt.MapFrom(src => src.SerialNumberStart)).ForMember(dest => dest.Vat, opt => opt.MapFrom(src => src.Vat)).ForMember(dest => dest.PurchasePrice, opt => opt.MapFrom(src => src.PurchasePrice)).ForMember(dest => dest.PurchaseCurrencyId, opt => opt.MapFrom(src => src.PurchaseCurrencyId)).ForMember(dest => dest.SalePrice, opt => opt.MapFrom(src => src.SalePrice)).ForMember(dest => dest.SalePriceCurrencyId, opt => opt.MapFrom(src => src.SalePriceCurrencyId)).ReverseMap();
        CreateMap<StockUpdateDto, Stock>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.ModelName, opt => opt.MapFrom(src => src.ModelName)).ForMember(dest => dest.ModelCode, opt => opt.MapFrom(src => src.ModelCode)).ForMember(dest => dest.ModelType, opt => opt.MapFrom(src => src.ModelType)).ForMember(dest => dest.UnitId, opt => opt.MapFrom(src => src.UnitId)).ForMember(dest => dest.SerialTracking, opt => opt.MapFrom(src => src.SerialTracking)).ForMember(dest => dest.VirtualSeries, opt => opt.MapFrom(src => src.VirtualSeries)).ForMember(dest => dest.SerialNumberStart, opt => opt.MapFrom(src => src.SerialNumberStart)).ForMember(dest => dest.Vat, opt => opt.MapFrom(src => src.Vat)).ForMember(dest => dest.PurchasePrice, opt => opt.MapFrom(src => src.PurchasePrice)).ForMember(dest => dest.PurchaseCurrencyId, opt => opt.MapFrom(src => src.PurchaseCurrencyId)).ForMember(dest => dest.SalePrice, opt => opt.MapFrom(src => src.SalePrice)).ForMember(dest => dest.SalePriceCurrencyId, opt => opt.MapFrom(src => src.SalePriceCurrencyId)).ReverseMap();

        CreateMap<StockGroup, StockGroup>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroup, StockGroupDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroupCreateDto, StockGroup>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();
        CreateMap<StockGroupUpdateDto, StockGroup>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();

        CreateMap<StockBrand, StockBrand>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockBrand, StockBrandDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockBrandCreateDto, StockBrand>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();
        CreateMap<StockBrandUpdateDto, StockBrand>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ReverseMap();

        CreateMap<StockGroupBrandMap, StockGroupBrandMap>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroupBrandMap, StockGroupBrandMapDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroupBrandMapCreateDto, StockGroupBrandMap>().ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();
        CreateMap<StockGroupBrandMapUpdateDto, StockGroupBrandMap>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockBrandId, opt => opt.MapFrom(src => src.StockBrandId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();

        CreateMap<FaultType, FaultType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<FaultType, FaultTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<FaultTypeCreateDto, FaultType>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<FaultTypeUpdateDto, FaultType>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();

        CreateMap<StockGroupFaultTypeMap, StockGroupFaultTypeMap>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroupFaultTypeMap, StockGroupFaultTypeMapDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockGroupFaultTypeMapCreateDto, StockGroupFaultTypeMap>().ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();
        CreateMap<StockGroupFaultTypeMapUpdateDto, StockGroupFaultTypeMap>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();

        CreateMap<StockMovement, StockMovement>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovement, StockMovementDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.StockMovementTypeId, opt => opt.MapFrom(src => src.StockMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity)).ForMember(dest => dest.InvoiceId, opt => opt.MapFrom(src => src.InvoiceId)).ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovementCreateDto, StockMovement>().ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.StockMovementTypeId, opt => opt.MapFrom(src => src.StockMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity)).ForMember(dest => dest.InvoiceId, opt => opt.MapFrom(src => src.InvoiceId)).ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ReverseMap();
        CreateMap<StockMovementUpdateDto, StockMovement>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.StockMovementTypeId, opt => opt.MapFrom(src => src.StockMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity)).ForMember(dest => dest.InvoiceId, opt => opt.MapFrom(src => src.InvoiceId)).ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ReverseMap();

        CreateMap<StockMovementStockSerialMap, StockMovementStockSerialMap>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovementStockSerialMap, StockMovementStockSerialMapDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.StockMovementId, opt => opt.MapFrom(src => src.StockMovementId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovementStockSerialMapCreateDto, StockMovementStockSerialMap>().ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.StockMovementId, opt => opt.MapFrom(src => src.StockMovementId)).ReverseMap();
        CreateMap<StockMovementStockSerialMapUpdateDto, StockMovementStockSerialMap>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.StockMovementId, opt => opt.MapFrom(src => src.StockMovementId)).ReverseMap();

        CreateMap<StockMovementType, StockMovementType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovementType, StockMovementTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.InOutCode, opt => opt.MapFrom(src => src.InOutCode)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockMovementTypeCreateDto, StockMovementType>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.InOutCode, opt => opt.MapFrom(src => src.InOutCode)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<StockMovementTypeUpdateDto, StockMovementType>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.InOutCode, opt => opt.MapFrom(src => src.InOutCode)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();

        CreateMap<StockSerial, StockSerial>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockSerial, StockSerialDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.SerialNumber, opt => opt.MapFrom(src => src.SerialNumber)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockSerialCreateDto, StockSerial>().ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.SerialNumber, opt => opt.MapFrom(src => src.SerialNumber)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ReverseMap();
        CreateMap<StockSerialUpdateDto, StockSerial>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockId, opt => opt.MapFrom(src => src.StockId)).ForMember(dest => dest.SerialNumber, opt => opt.MapFrom(src => src.SerialNumber)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.WarehouseId, opt => opt.MapFrom(src => src.WarehouseId)).ReverseMap();

        CreateMap<StockSerialWarranty, StockSerialWarranty>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockSerialWarranty, StockSerialWarrantyDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.WarrantyTypeId, opt => opt.MapFrom(src => src.WarrantyTypeId)).ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate)).ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockSerialWarrantyCreateDto, StockSerialWarranty>().ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.WarrantyTypeId, opt => opt.MapFrom(src => src.WarrantyTypeId)).ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate)).ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ReverseMap();
        CreateMap<StockSerialWarrantyUpdateDto, StockSerialWarranty>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockSerialId, opt => opt.MapFrom(src => src.StockSerialId)).ForMember(dest => dest.WarrantyTypeId, opt => opt.MapFrom(src => src.WarrantyTypeId)).ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.StartDate)).ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.EndDate)).ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status)).ReverseMap();

        CreateMap<StockType, StockType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockType, StockTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockTypeCreateDto, StockType>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<StockTypeUpdateDto, StockType>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();

        CreateMap<StockTypeGroupMap, StockTypeGroupMap>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockTypeGroupMap, StockTypeGroupMapDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockTypeId, opt => opt.MapFrom(src => src.StockTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<StockTypeGroupMapCreateDto, StockTypeGroupMap>().ForMember(dest => dest.StockTypeId, opt => opt.MapFrom(src => src.StockTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();
        CreateMap<StockTypeGroupMapUpdateDto, StockTypeGroupMap>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.StockTypeId, opt => opt.MapFrom(src => src.StockTypeId)).ForMember(dest => dest.StockGroupId, opt => opt.MapFrom(src => src.StockGroupId)).ReverseMap();

        CreateMap<Warehouse, Warehouse>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Warehouse, WarehouseDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<WarehouseCreateDto, Warehouse>().ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<WarehouseUpdateDto, Warehouse>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
    }
}
