using AutoMapper;
using ExpressDesk360.Model.Dtos.TicketModule.TicketServicePrice.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketServicePrice.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketType.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketType.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.Ticket.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.Ticket.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMessageFile.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMessageFile.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovement.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovement.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketPriority.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketPriority.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovementType.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovementType.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketStatus.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketStatus.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMessage.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMessage.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketStaff.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketStaff.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovementFile.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketMovementFile.Queries;
using ExpressDesk360.Model.Dtos.TicketModule.TicketFile.Commands;
using ExpressDesk360.Model.Dtos.TicketModule.TicketFile.Queries;
using ExpressDesk360.Model.Entities.TicketModule;

namespace ExpressDesk360.Business.Mappings;

public class TicketModuleMappingProfiles : Profile
{
    public TicketModuleMappingProfiles()
    {
        CreateMap<Ticket, Ticket>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Ticket, TicketDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketTypeId, opt => opt.MapFrom(src => src.TicketTypeId)).ForMember(dest => dest.TicketPriorityId, opt => opt.MapFrom(src => src.TicketPriorityId)).ForMember(dest => dest.RequesterId, opt => opt.MapFrom(src => src.RequesterId)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.CompanyProductId, opt => opt.MapFrom(src => src.CompanyProductId)).ForMember(dest => dest.Number, opt => opt.MapFrom(src => src.Number)).ForMember(dest => dest.LastTicketMovementTypeId, opt => opt.MapFrom(src => src.LastTicketMovementTypeId)).ForMember(dest => dest.Title, opt => opt.MapFrom(src => src.Title)).ForMember(dest => dest.TicketDescription, opt => opt.MapFrom(src => src.TicketDescription)).ForMember(dest => dest.RemoteSupport, opt => opt.MapFrom(src => src.RemoteSupport)).ForMember(dest => dest.UnderWarranty, opt => opt.MapFrom(src => src.UnderWarranty)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForMember(dest => dest.DueDate, opt => opt.MapFrom(src => src.DueDate)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<Ticket, TicketReportDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.TicketTypeId, opt => opt.MapFrom(src => src.TicketTypeId))
            .ForMember(dest => dest.TicketTypeName, opt => opt.MapFrom(src => src.TicketType != null ? src.TicketType.Name : null))
            .ForMember(dest => dest.TicketPriorityId, opt => opt.MapFrom(src => src.TicketPriorityId))
            .ForMember(dest => dest.TicketPriorityName, opt => opt.MapFrom(src => src.TicketPriority != null ? src.TicketPriority.Name : null))
            .ForMember(dest => dest.RequesterId, opt => opt.MapFrom(src => src.RequesterId))
            .ForMember(dest => dest.RequesterName, opt => opt.MapFrom(src => src.Requester != null ? src.Requester.Name + " " + src.Requester.SurName : null))
            .ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId))
            .ForMember(dest => dest.CompanyName, opt => opt.MapFrom(src => src.Company != null ? src.Company.Name : null))
            .ForMember(dest => dest.CompanyProductId, opt => opt.MapFrom(src => src.CompanyProductId))
            .ForMember(dest => dest.CompanyProductName, opt => opt.MapFrom(src => src.CompanyProduct != null ? src.CompanyProduct.Name : null))
            .ForMember(dest => dest.Number, opt => opt.MapFrom(src => src.Number))
            .ForMember(dest => dest.LastTicketMovementTypeId, opt => opt.MapFrom(src => src.LastTicketMovementTypeId))
            .ForMember(dest => dest.LastTicketMovementTypeName, opt => opt.MapFrom(src => src.LastTicketMovementType != null ? src.LastTicketMovementType.Name : null))
            .ForMember(dest => dest.Title, opt => opt.MapFrom(src => src.Title))
            .ForMember(dest => dest.TicketDescription, opt => opt.MapFrom(src => src.TicketDescription))
            .ForMember(dest => dest.RemoteSupport, opt => opt.MapFrom(src => src.RemoteSupport))
            .ForMember(dest => dest.UnderWarranty, opt => opt.MapFrom(src => src.UnderWarranty))
            .ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date))
            .ForMember(dest => dest.DueDate, opt => opt.MapFrom(src => src.DueDate))
            .ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted))
            .ForMember(dest => dest.TicketStaffs, opt => opt.MapFrom(src => src.TicketStaffs))
            .ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketCreateDto, Ticket>().ForMember(dest => dest.TicketTypeId, opt => opt.MapFrom(src => src.TicketTypeId)).ForMember(dest => dest.TicketPriorityId, opt => opt.MapFrom(src => src.TicketPriorityId)).ForMember(dest => dest.RequesterId, opt => opt.MapFrom(src => src.RequesterId)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.CompanyProductId, opt => opt.MapFrom(src => src.CompanyProductId)).ForMember(dest => dest.Title, opt => opt.MapFrom(src => src.Title)).ForMember(dest => dest.TicketDescription, opt => opt.MapFrom(src => src.TicketDescription)).ReverseMap();
        CreateMap<TicketUpdateDto, Ticket>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketTypeId, opt => opt.MapFrom(src => src.TicketTypeId)).ForMember(dest => dest.TicketPriorityId, opt => opt.MapFrom(src => src.TicketPriorityId)).ForMember(dest => dest.CompanyId, opt => opt.MapFrom(src => src.CompanyId)).ForMember(dest => dest.CompanyProductId, opt => opt.MapFrom(src => src.CompanyProductId)).ForMember(dest => dest.Title, opt => opt.MapFrom(src => src.Title)).ForMember(dest => dest.TicketDescription, opt => opt.MapFrom(src => src.TicketDescription)).ReverseMap();
        
        CreateMap<TicketFile, TicketFile>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketFile, TicketFileDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketFileCreateDto, TicketFile>().ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        CreateMap<TicketFileUpdateDto, TicketFile>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        
        CreateMap<TicketMessage, TicketMessage>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMessage, TicketMessageDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.IsSystem, opt => opt.MapFrom(src => src.IsSystem)).ForMember(dest => dest.SenderId, opt => opt.MapFrom(src => src.SenderId)).ForMember(dest => dest.ExternalAccess, opt => opt.MapFrom(src => src.ExternalAccess)).ForMember(dest => dest.Content, opt => opt.MapFrom(src => src.Content)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMessageCreateDto, TicketMessage>().ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.IsSystem, opt => opt.MapFrom(src => src.IsSystem)).ForMember(dest => dest.SenderId, opt => opt.MapFrom(src => src.SenderId)).ForMember(dest => dest.ExternalAccess, opt => opt.MapFrom(src => src.ExternalAccess)).ForMember(dest => dest.Content, opt => opt.MapFrom(src => src.Content)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ReverseMap();
        CreateMap<TicketMessageUpdateDto, TicketMessage>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.IsSystem, opt => opt.MapFrom(src => src.IsSystem)).ForMember(dest => dest.SenderId, opt => opt.MapFrom(src => src.SenderId)).ForMember(dest => dest.ExternalAccess, opt => opt.MapFrom(src => src.ExternalAccess)).ForMember(dest => dest.Content, opt => opt.MapFrom(src => src.Content)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ReverseMap();
        
        CreateMap<TicketMessageFile, TicketMessageFile>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMessageFile, TicketMessageFileDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketMessageId, opt => opt.MapFrom(src => src.TicketMessageId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMessageFileCreateDto, TicketMessageFile>().ForMember(dest => dest.TicketMessageId, opt => opt.MapFrom(src => src.TicketMessageId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        CreateMap<TicketMessageFileUpdateDto, TicketMessageFile>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketMessageId, opt => opt.MapFrom(src => src.TicketMessageId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        
        CreateMap<TicketMovement, TicketMovement>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovement, TicketMovementDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.TicketMovementTypeId, opt => opt.MapFrom(src => src.TicketMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.ShippingId, opt => opt.MapFrom(src => src.ShippingId)).ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovementCreateDto, TicketMovement>().ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.TicketMovementTypeId, opt => opt.MapFrom(src => src.TicketMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.ShippingId, opt => opt.MapFrom(src => src.ShippingId)).ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<TicketMovementUpdateDto, TicketMovement>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.TicketMovementTypeId, opt => opt.MapFrom(src => src.TicketMovementTypeId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.ShippingId, opt => opt.MapFrom(src => src.ShippingId)).ForMember(dest => dest.FaultTypeId, opt => opt.MapFrom(src => src.FaultTypeId)).ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        
        CreateMap<TicketMovementFile, TicketMovementFile>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovementFile, TicketMovementFileDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovementFileCreateDto, TicketMovementFile>().ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        CreateMap<TicketMovementFileUpdateDto, TicketMovementFile>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketMovementId, opt => opt.MapFrom(src => src.TicketMovementId)).ForMember(dest => dest.FileId, opt => opt.MapFrom(src => src.FileId)).ReverseMap();
        
        CreateMap<TicketMovementType, TicketMovementType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovementType, TicketMovementTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.TicketStatusId, opt => opt.MapFrom(src => src.TicketStatusId)).ForMember(dest => dest.Accessible, opt => opt.MapFrom(src => src.Accessible)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.InformationText, opt => opt.MapFrom(src => src.InformationText)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketMovementTypeCreateDto, TicketMovementType>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.TicketStatusId, opt => opt.MapFrom(src => src.TicketStatusId)).ForMember(dest => dest.Accessible, opt => opt.MapFrom(src => src.Accessible)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.InformationText, opt => opt.MapFrom(src => src.InformationText)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<TicketMovementTypeUpdateDto, TicketMovementType>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.TicketStatusId, opt => opt.MapFrom(src => src.TicketStatusId)).ForMember(dest => dest.Accessible, opt => opt.MapFrom(src => src.Accessible)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.InformationText, opt => opt.MapFrom(src => src.InformationText)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        
        CreateMap<TicketPriority, TicketPriority>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketPriority, TicketPriorityDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.Icon, opt => opt.MapFrom(src => src.Icon)).ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Value)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketPriorityCreateDto, TicketPriority>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.Icon, opt => opt.MapFrom(src => src.Icon)).ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Value)).ReverseMap();
        CreateMap<TicketPriorityUpdateDto, TicketPriority>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Color, opt => opt.MapFrom(src => src.Color)).ForMember(dest => dest.Icon, opt => opt.MapFrom(src => src.Icon)).ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Value)).ReverseMap();
        
        CreateMap<TicketServicePrice, TicketServicePrice>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketServicePrice, TicketServicePriceDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.MaterialPrice, opt => opt.MapFrom(src => src.MaterialPrice)).ForMember(dest => dest.ServicePrice, opt => opt.MapFrom(src => src.ServicePrice)).ForMember(dest => dest.AnotherPrice, opt => opt.MapFrom(src => src.AnotherPrice)).ForMember(dest => dest.TaxAmount, opt => opt.MapFrom(src => src.TaxAmount)).ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount)).ForMember(dest => dest.ServiceTotal, opt => opt.MapFrom(src => src.ServiceTotal)).ForMember(dest => dest.CurrencyId, opt => opt.MapFrom(src => src.CurrencyId)).ForMember(dest => dest.ExchangeRate, opt => opt.MapFrom(src => src.ExchangeRate)).ForMember(dest => dest.ServiceDescription, opt => opt.MapFrom(src => src.ServiceDescription)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketServicePriceCreateDto, TicketServicePrice>().ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.MaterialPrice, opt => opt.MapFrom(src => src.MaterialPrice)).ForMember(dest => dest.ServicePrice, opt => opt.MapFrom(src => src.ServicePrice)).ForMember(dest => dest.AnotherPrice, opt => opt.MapFrom(src => src.AnotherPrice)).ForMember(dest => dest.TaxAmount, opt => opt.MapFrom(src => src.TaxAmount)).ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount)).ForMember(dest => dest.ServiceTotal, opt => opt.MapFrom(src => src.ServiceTotal)).ForMember(dest => dest.CurrencyId, opt => opt.MapFrom(src => src.CurrencyId)).ForMember(dest => dest.ExchangeRate, opt => opt.MapFrom(src => src.ExchangeRate)).ForMember(dest => dest.ServiceDescription, opt => opt.MapFrom(src => src.ServiceDescription)).ReverseMap();
        CreateMap<TicketServicePriceUpdateDto, TicketServicePrice>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.MaterialPrice, opt => opt.MapFrom(src => src.MaterialPrice)).ForMember(dest => dest.ServicePrice, opt => opt.MapFrom(src => src.ServicePrice)).ForMember(dest => dest.AnotherPrice, opt => opt.MapFrom(src => src.AnotherPrice)).ForMember(dest => dest.TaxAmount, opt => opt.MapFrom(src => src.TaxAmount)).ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount)).ForMember(dest => dest.ServiceTotal, opt => opt.MapFrom(src => src.ServiceTotal)).ForMember(dest => dest.CurrencyId, opt => opt.MapFrom(src => src.CurrencyId)).ForMember(dest => dest.ExchangeRate, opt => opt.MapFrom(src => src.ExchangeRate)).ForMember(dest => dest.ServiceDescription, opt => opt.MapFrom(src => src.ServiceDescription)).ReverseMap();
        
        CreateMap<TicketStaff, TicketStaff>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketStaff, TicketStaffDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate)).ForMember(dest => dest.UserFullName, opt => opt.MapFrom(src => src.User != null ? src.User.Name + " " + src.User.SurName : null)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketStaffCreateDto, TicketStaff>().ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate)).ReverseMap();
        CreateMap<TicketStaffUpdateDto, TicketStaff>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.TicketId, opt => opt.MapFrom(src => src.TicketId)).ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId)).ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate)).ReverseMap();
        
        CreateMap<TicketStatus, TicketStatus>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketStatus, TicketStatusDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketStatusCreateDto, TicketStatus>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<TicketStatusUpdateDto, TicketStatus>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        
        CreateMap<TicketType, TicketType>().ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketType, TicketTypeDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ForAllMembers(opt => opt.Condition((src, dest, srcMember, destMember) => !Equals(srcMember, destMember)));
        CreateMap<TicketTypeCreateDto, TicketType>().ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
        CreateMap<TicketTypeUpdateDto, TicketType>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id)).ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name)).ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description)).ReverseMap();
    }
}
