<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ExpressDesk360.DataAccess\ExpressDesk360.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Concrete\CompanyModule\" />
    <Folder Include="Concrete\InvoiceModule\" />
    <Folder Include="Concrete\UserModule\" />
    <Folder Include="Concrete\TicketModule\" />
    <Folder Include="Concrete\ProductionModule\" />
    <Folder Include="Concrete\ProjectModule\" />
    <Folder Include="Concrete\ShippingModule\" />
    <Folder Include="Concrete\TaskModule\" />
    <Folder Include="Concrete\Common\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
